// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGp4tS7S7IJKsu5WjDWQrwoT7OAfZ2tEw',
    appId: '1:266306274885:web:5bd206eeeb660fddbac52c',
    messagingSenderId: '266306274885',
    projectId: 'fir-flutter-32f68',
    authDomain: 'fir-flutter-32f68.firebaseapp.com',
    storageBucket: 'fir-flutter-32f68.firebasestorage.app',
    measurementId: 'G-JK5HC6GEQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcPWNZxJnAwD7UWxyK4yYngCu0fbqSTTo',
    appId: '1:266306274885:android:84402ac9aca4f5a3bac52c',
    messagingSenderId: '266306274885',
    projectId: 'fir-flutter-32f68',
    storageBucket: 'fir-flutter-32f68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnSZaHHCuLYYycqV9zJKEl9QcJZqHT2w8',
    appId: '1:266306274885:ios:e7ac304aae0d6f7abac52c',
    messagingSenderId: '266306274885',
    projectId: 'fir-flutter-32f68',
    storageBucket: 'fir-flutter-32f68.firebasestorage.app',
    iosBundleId: 'com.caydenmtheseira.healthify',
  );
}
